---
- name: Add ppa:git-core/ppa to install latest git
  apt_repository:
    repo: 'ppa:git-core/ppa'
    state: present
  become: true

- name: Install Git packages.
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ gitconfig_packages }}"
  become: true

- name: Configure gitconfig file.
  template:
    src: gitconfig.j2
    dest: "~{{ gitconfig_user }}/.gitconfig"
    owner: "{{ gitconfig_user }}"
    group: "{{ gitconfig_user }}"
    validate: git config -f %s --list
  when: gitconfig_set

- name: Configure gitignore file.
  template:
    src: gitignore.j2
    dest: "~{{ gitconfig_user }}/{{ gitconfig.core.excludesfile | basename }}"
    owner: "{{ gitconfig_user }}"
    group: "{{ gitconfig_user }}"
  when: gitconfig_set_ignore

- name: Configure Git commit message template.
  template:
    src: gitmessage.j2
    dest: "~{{ gitconfig_user }}/{{ gitconfig.commit.template | basename }}"
    owner: "{{ gitconfig_user }}"
    group: "{{ gitconfig_user }}"
  when: gitconfig_set_commit_message
